import type { Metadata } from "next";

import { Manrope } from "next/font/google";
import { GeistMono } from "geist/font/mono";
import { CopilotKit } from "@copilotkit/react-core";
import "./globals.css";
import "@copilotkit/react-ui/styles.css";
import { ThemeProvider } from "@/components/providers/theme-provider";

const manrope = Manrope({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-manrope",
});

export const metadata: Metadata = {
  title: "AG-UI Canvas | CopilotKit with Mastra",
  description: "Generated by CopilotKit with Mastra",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={`${manrope.variable} ${GeistMono.variable}`}>
      <body className="subpixel-antialiased">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <CopilotKit
            runtimeUrl="/api/copilotkit"
            agent="sample_agent"
            showDevConsole={process.env.NODE_ENV !== 'production'}
            publicApiKey={process.env.NEXT_PUBLIC_COPILOTKIT_API_KEY}
          >
            {children}
          </CopilotKit>
        </ThemeProvider>
      </body>
    </html>
  );
}
